galaxy_info:
  author: "General Electric Company"
  description: "Ansible role to apply Ubuntu 16.04 CIS baseline"
  company: "General Electric Company"
  license: "All Rights Reserved"
  min_ansible_version: 2.4

  platforms:
  - name: Ubuntu
    versions:
      - 16

dependencies: []
