- name: "4.1.1.x | Ensure Auditd is installed"
  apt:
    name: auditd
    state: present
  when: ubu16gsa_auditd_config == true
  tags:
    - id_4.1.1x

- name: "4.1.1.3 | Ensure audit logs are not automatically deleted"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file_action"
      line: "max_log_file_action = keep_logs"
      state: present
  when: ubu16gsa_auditd_config == true
  tags:
      - id_4.1.1.3

- name: "4.1.2 | Ensure auditd service is enabled"
  systemd:
      name: auditd
      state: started
      enabled: yes
  when: ubu16gsa_auditd_config == true
  tags:
      - id_4.1.2

- name: "4.1.3 | Ensure auditing for processes that start prior to auditd is enabled"
  lineinfile:
      dest: /etc/default/grub
      regexp: "^GRUB_CMDLINE_LINUX="
      line: 'GRUB_CMDLINE_LINUX="audit=1"'
      state: present
      create: yes
  when: ubu16gsa_auditd_config == true
  tags:
      - id_4.1.3

- name: "4.1.3 | Ensure auditing for processes that start prior to auditd is enabled"
  command: update-grub
  when: ubu16gsa_auditd_config == true
  tags:
      - id_4.1.3

- name: "4.1.4-4.1.18 | Configure Auditd rules and configurations."
  template:
    src: audit_rules
    dest: /etc/audit/audit.rules
  when: ubu16gsa_auditd_config == true
  tags:
      - id_4.1.4
      - id_4.1.5
      - id_4.1.6
      - id_4.1.7
      - id_4.1.8
      - id_4.1.9
      - id_4.1.10
      - id_4.1.11
      - id_4.1.12
      - id_4.1.13
      - id_4.1.14
      - id_4.1.15
      - id_4.1.16
      - id_4.1.17
      - id_4.1.18

- name: "4.2.1.1 Ensure rsyslog Service is enabled"
  systemd:
      name: rsyslog
      enabled: yes
      state: started
  when: ubu16gsa_logging == "rsyslog" and ubu16gsa_config_logging == true
  tags:
      - id_4.2.1.1

- name: "4.2.1.3 | Ensure rsyslog default file permissions configured"
  template:
      src: rsyslog
      dest: /etc/rsyslog.conf
  when: ubu16gsa_logging == "rsyslog" and ubu16gsa_config_logging == true
  tags:
      - id_4.2.1.3

- name: "Update rsyslog default config"
  template:
      src: rsyslog-50-default
      dest: /etc/rsyslog.d/50-default.conf
  when: ubu16gsa_logging == "rsyslog" and ubu16gsa_config_logging == true

- name: "Update rsyslog logrotate config"
  template:
      src: logrotate-rsyslog
      dest: /etc/logrotate.d/rsyslog
  when: ubu16gsa_logging == "rsyslog" and ubu16gsa_config_logging == true

- name: "Update logrotate config"
  template:
      src: logrotate
      dest: /etc/logrotate.conf

- name: "Remove /var/log/auth.log"
  file:
      dest: /var/log/auth.log
      state: absent

- name: "Remove /var/log/syslog"
  file:
      dest: /var/log/syslog
      state: absent
  
- name: "4.2.3 | Ensure rsyslog or syslog-ng is installed"
  apt:
      name: rsyslog
      state: present
  when: ubu16gsa_logging == "rsyslog" and ubu16gsa_config_logging == true
  tags:
      - id_4.2.3
