---
driver:
  name: vagrant
  driver_config:
    http_proxy: <%= ENV['http_proxy'] || nil %>
    https_proxy: <%= ENV['https_proxy'] || nil %>
  vagrantfiles:
    - kitchen_vagrant_block.rb

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  http_proxy: <%= ENV['http_proxy'] || nil %>
  https_proxy: <%= ENV['https_proxy'] || nil %>
  
transport:
  max_ssh_sessions: 5

platforms:
  - name: ubuntu-16-04
    driver_config:
      box: bento/ubuntu-16.04

verifier:
  name: inspec
  sudo: true

suites:
  - name: default
